<?php
    include("includes/connect.inc");
?>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="stylesheets/main.css" rel="stylesheet">
    <link href="stylesheets/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <script src="stylesheets/bootstrap/js/bootstrap.min.js"></script>
    <title>Blog</title>
</head>
<body>
